#!/bin/bash
# uvr - uv run wrapper
# Uses nearest project with pyproject.toml.

dir="$PWD"
while [[ -n "$dir" ]]; do
    [[ -f "$dir/pyproject.toml" || -f "$dir/.python-version" ]] && break
    dir="${dir%/*}"
done

exec uv --quiet --project "${dir:-$HOME}" run --no-sync "$@"
